---
- name: Our first isilon playook
  hosts: localhost
  gather_facts: no

  tasks:
          - name: Get attributes, access_zones and nodes of the Isilon cluster
            dellemc_isilon_gatherfacts:
                    onefs_host: "{{ onefs_host }}"
                    port_no: "{{ isilonport }}"
                    verify_ssl: "{{ verify_ssl }}"
                    api_user: "{{ api_user }}"
                    api_password: "{{ api_password }}"
                    gather_subset:
                            - attributes
                            - access_zones
                            - nodes
